# This is a basic workflow to help you get started with Actions

name: Trivy Scanning

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Aqua Security Trivy - UNKOWN and LOW Severities
        # You may pin to the exact commit or the version.
        # uses: aquasecurity/trivy-action@8eccb5539730451af599c84f444c6d6cf0fc2bb0
        uses: aquasecurity/trivy-action@0.0.20
        with:
          # image reference(for backward compatibility)
          image-ref: ruby:2.4.0
          # exit code when vulnerabilities were found
          exit-code: 0
          # severities of vulnerabilities to be displayed
          severity: UNKNOWN,LOW
          
      - name: Aqua Security Trivy - MEDIUM Severity
        # You may pin to the exact commit or the version.
        # uses: aquasecurity/trivy-action@8eccb5539730451af599c84f444c6d6cf0fc2bb0
        uses: aquasecurity/trivy-action@0.0.20
        with:
          # image reference(for backward compatibility)
          image-ref: ruby:2.4.0
          # exit code when vulnerabilities were found
          exit-code: 0
          # severities of vulnerabilities to be displayed
          severity: MEDIUM
          
      - name: Aqua Security Trivy - HIGH and CRITICAL Severities
        # You may pin to the exact commit or the version.
        # uses: aquasecurity/trivy-action@8eccb5539730451af599c84f444c6d6cf0fc2bb0
        uses: aquasecurity/trivy-action@0.0.20
        with:
          # image reference(for backward compatibility)
          image-ref: ruby:2.4.0
          # exit code when vulnerabilities were found
          exit-code: 0
          # severities of vulnerabilities to be displayed
          severity: HIGH,CRITICAL

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
